### ISSUE TITLE
[REFACTOR]: Softening or disabling `prefer-readonly-parameter-types`

### ISSUE THREAD

**Issue by galyfray** [Libra-foundation/eslint-configs#4]
### Summary

The rule `prefer-readonly-parameter-types` is meant to remember the developer to prefer read-only types when possible.
This rule adds more information about what to expect from a function or a method.

### Motivation

However, Typescript has no way to explicitly tell when we are planing on muting an object. 
Furthermore, the way ESLint determine if an object is read-only is rather obscure and strict. 
I also would like to point out that few other projects take the time to use this rule and assert when they are only reading data from an object.

This is why I would like to propose to at least softening this rule and if possible to disable it completely.
While I do like to explicitly tell when mutating an object or when we are only reading data from it, this adds a non-negligible amount of boilerplate to the process of developing.

### Implementation

Softening :
```javascript
   "@typescript-eslint/prefer-readonly-parameter-types": [
        "error",
        {
          "checkParameterProperties": false,
          "ignoreInferredTypes": true,
          "treatMethodsAsReadonly": true
        }
   ]
```
Disabling : 
remove the rule from the rule set

### Checks

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

**Comment by galyfray** [comment]
@Beladric @Valentin271 May I get your feedback on this ?

**Comment by Valentin271** [comment]
I think it's a good idea to start by softening the rule and if we still think its too restrictive, disable it.

**Comment by Beladric** [comment]
Hello @galyfray. I agree with @Valentin271, try to soften it and if warnings continue we will disable it.
